name: Publish RC for Pull Request

on: 
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  packages: write
  # workaround for https://github.com/cli/cli/issues/6274
  repository-projects: read
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if changeset is in prerelease mode
        id: check-in-pre
        run: echo "pre=$(test -r .changeset/pre.json; echo $?)"  >> "$GITHUB_OUTPUT"
      - name: Get version to be released
        id: get-version
        run: node -e "console.log('version=' + require('./package.json').version)" >> "$GITHUB_OUTPUT"
      - name: Check if the image for the version is already pushed
        id: tag-list
        run: |
          echo "taglist=$(curl -H "Authorization: Bearer $(echo ${GITHUB_TOKEN} | base64)" https://ghcr.io/v2/${GITHUB_REPOSITORY}/tags/list)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Log in to Docker Hub
        if: >-
          ${{steps.check-in-pre.outputs.pre == 0 &&
          ! contains(fromJson(steps.tag-list.outputs.taglist).tags, steps.get-version.outputs.version)}}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: >-
          ${{steps.check-in-pre.outputs.pre == 0 &&
          ! contains(fromJson(steps.tag-list.outputs.taglist).tags, steps.get-version.outputs.version)}}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
          # 必要に応じて秘密情報を build-args を追加
          # build-args: |
          #   "XXX_KEY=${{ secrets.XXX_KEY }}"
